### PR TITLE
Sync sub_part field for keys based on VARCHAR

### PR DESCRIPTION
**Pull request by samrussell**
This is a tidier version of pull request #10, with whitespace fixed up.

### CODE REVIEW

**Comment by willbryant** [comment]
This makes the test suite fail on postgresql (try running `docker build .` from the root).

Most of the failures are fixed by adding the following diff to initialise variables whenever an empty Key object is constructed, so that in the case where sub_part is not serialised, it is set to 0:

```
diff --git a/src/schema.h b/src/schema.h
index 3d3cc44..f2e35cd 100644
--- a/src/schema.h
+++ b/src/schema.h
@@ -63,7 +63,7 @@ struct Key {
 	ColumnIndices columns;
 
 	inline Key(const string &name, bool unique, size_t sub_part = 0): name(name), unique(unique), sub_part(sub_part) {}
-	inline Key() {}
+	inline Key(): unique(false), sub_part(0) {}
 
 	inline bool operator <(const Key &other) const { return (unique != other.unique ? unique : name < other.name); }
 	inline bool operator ==(const Key &other) const { return (name == other.name && unique == other.unique && columns == other.columns && sub_part == other.sub_part); }
```

But there is still one test that still fails:

```
===============================================================================
Error: test_selects_the_first_unique_key_with_no_nullable_columns_if_there_is_no_primary_key_for_postgresql(SchemaFromTest)
: RuntimeError: expected command [37, [{"tables"=>[{"name"=>"noprimarytbl", "columns"=>[{"name"=>"nullable", "column_type"=>"INT", "size"=>4}, {"name"=>"version", "column_type"=>"VARCHAR", "size"=>255, "nullable"=>false}, {"name"=>"name", "column_type"=>"VARCHAR", "size"=>255}, {"name"=>"non_nullable", "column_type"=>"INT", "size"=>4, "nullable"=>false}], "primary_key_columns"=>[1], "keys"=>[{"name"=>"correct_key", "unique"=>true, "columns"=>[1]}, {"name"=>"ignored_key", "unique"=>true, "columns"=>[0, 1]}, {"name"=>"name_key", "unique"=>true, "columns"=>[2], "sub_part"=>250}, {"name"=>"non_nullable_key", "unique"=>true, "columns"=>[3]}, {"name"=>"version_and_name_key", "unique"=>true, "columns"=>[1, 2]}, {"name"=>"everything_key", "unique"=>false, "columns"=>[2, 0, 1]}, {"name"=>"not_unique_key", "unique"=>false, "columns"=>[3]}]}]}]] but received [37, [{"tables"=>[{"name"=>"noprimarytbl", "columns"=>[{"name"=>"nullable", "column_type"=>"INT", "size"=>4}, {"name"=>"version", "column_type"=>"VARCHAR", "size"=>255, "nullable"=>false}, {"name"=>"name", "column_type"=>"VARCHAR", "size"=>255}, {"name"=>"non_nullable", "column_type"=>"INT", "size"=>4, "nullable"=>false}], "primary_key_columns"=>[1], "keys"=>[{"name"=>"correct_key", "unique"=>true, "columns"=>[1]}, {"name"=>"ignored_key", "unique"=>true, "columns"=>[0, 1]}, {"name"=>"non_nullable_key", "unique"=>true, "columns"=>[3]}, {"name"=>"version_and_name_key", "unique"=>true, "columns"=>[1, 2]}, {"name"=>"everything_key", "unique"=>false, "columns"=>[2, 0, 1]}, {"name"=>"not_unique_key", "unique"=>false, "columns"=>[3]}]}]}]]
/tmp/test/test_helper.rb:317:in `expect_command'
../test/schema_from_test.rb:38:in `block in <class:SchemaFromTest>'
/tmp/test/test_helper.rb:468:in `instance_eval'
/tmp/test/test_helper.rb:468:in `block (2 levels) in test_each'
===============================================================================
```

Not sure why but name_key isn't showing up.  Does postgresql support that `ON noprimarytbl (name(250))` syntax?

**Comment by willbryant** [comment]
Looks to me like postgresql doesn't.  Would need to use a substring expression?

**Comment by samrussell** [comment]
Ah yup so make the change in src/sql_functions.h a bit smarter so it renders as left(name, 250) ?

**Comment by willbryant** [comment]
No updates for 3 years, so closing :(

**Pull request closed without merging**
