### PR TITLE
[PART 1] Greet the SSH server with a NOP so database server can be added to known hosts

### PR DESCRIPTION
**Pull request by dylanmckay**
This is the first part to #40.

Before this, ks would spin up multiple workers and would not allow any of them
to accept the host key fingerprint.

After this change, the host key prompt is asked before any syncing
actually happens. This ensures that the user always has a chance to
accept the host key fingerprint if necessary.

The SSH greeting will not prompt for anything if the host key
fingerprint is already known.

### CODE REVIEW

**Comment by dylanmckay** [comment]
With this change, he DB hosts need to be upgraded first though due to the addition of a new cmd line argument.

**Comment by aclemons** [comment]
Seems like a complicated solution. Couldn't you just append `-o BatchMode=yes` to the ssh command built by ks so that it actually just fails fast instead of prompting you with yes/no and then not actually accepting user input?

Then you'd get something like (here with 4 workers):

```
Kitchen Sync
Host key verification failed.
Killed by signal 1.
Error in the 'to' worker: Connection closed
Host key verification failed.
Killed by signal 1.
Host key verification failed.
Killed by signal 1.
Host key verification failed.
Killed by signal 1.
Kitchen Syncing failed.
```

Then the user knows that host verification failed and what to do.


```diff
$ git diff
diff --git a/src/ks.cpp b/src/ks.cpp
index 4547d53..7754499 100644
--- a/src/ks.cpp
+++ b/src/ks.cpp
@@ -51,7 +51,7 @@ int main(int argc, char *argv[]) {
                if (options.set_from_variables.empty()) options.set_from_variables = "-";
                if (options.cipher.empty()) options.cipher = "aes256-ctr";

-               const char *from_args[] = { ssh_binary.c_str(), "-C", "-c", options.cipher.c_str(), options.via.c_str(),
+               const char *from_args[] = { ssh_binary.c_str(), "-o", "BatchMode=yes", "-C", "-c", options.cipher.c_str(), options.via.c_str(),
                                                                        from_binary.c_str(), "from", options.from.host.c_str(), options.from.port.c_str(), options.from.database.c_str(), options.from.username.c_str(), options.from.password.c_str(), options.set_from_variables.c_str(), options.filters.c_str(), nullptr };
                const char **applicable_from_args = (options.via.empty() ? from_args + 5 : from_args);
```

**Comment by willbryant** [comment]
This does give clearer output, not just in the SSH host key verification case but also the case where the KS binary at the other end is missing.

Would BatchMode mean an unverified host key results in an error?

**Comment by aclemons** [comment]
Yes it would

**Comment by willbryant** [comment]
Dylan's solution has merit then.  I think it's more in line with most SSH-using programs, eg. rsync.

I'm leaning towards merging it in two releases to maximize compatibility.

**Comment by aclemons** [comment]
Yes, the rsync use case is simpler, since it only opens one remote shell, unlike here where each worker opens one. Then you can just type 'yes' at the prompt.

But if you absolutely want to handle this inside ks, do you actually need the new command on the server end? Couldn't you just run `/bin/true` or something? Then you don't need to worry about compatibility.

**Comment by willbryant** [comment]
That was actually Dylan's original code.  I suggested calling the real KS binary so that it could check that it is actually there.  Currently we give very poor user feedback if the binary is missing or has the wrong path, because the errors from N workers are intermingled.

**Comment by dylanmckay** [comment]
Is there anything more I can do on this?

If you'd like me to split this into two PRs so you can stage the release, I'm happy to.

**Comment by willbryant** [comment]
Sure, we might as well do that to minimize the impact eh.

**Comment by dylanmckay** [comment]
@willbryant I've staged this into two PRs - #38 and #40.

Let me know if you have any other suggestions.

**Comment by willbryant** [comment]
Looks good, thanks!

**Pull request merged**
